apiVersion: v1
kind: Service
metadata:
  name: execution-service
spec:
  selector:
    app: execution-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-service
  template:
    metadata:
      labels:
        app: execution-service
    spec:
      containers:
        - name: execution-service
          image: your-dockerhub/execution-service:latest
          envFrom:
            - configMapRef:
                name: alpha-oms-env
          ports:
            - containerPort: 50051
