apiVersion: v1
kind: Service
metadata:
  name: risk-service
spec:
  selector:
    app: risk-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-service
  template:
    metadata:
      labels:
        app: risk-service
    spec:
      containers:
        - name: risk-service
          image: your-dockerhub/risk-service:latest
          envFrom:
            - configMapRef:
                name: alpha-oms-env
          ports:
            - containerPort: 8002
