apiVersion: v1
kind: Service
metadata:
  name: stream-service
spec:
  selector:
    app: stream-service
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-service
  template:
    metadata:
      labels:
        app: stream-service
    spec:
      containers:
        - name: stream-service
          image: your-dockerhub/stream-service:latest
          envFrom:
            - configMapRef:
                name: alpha-oms-env
          ports:
            - containerPort: 8005
