apiVersion: v1
kind: Service
metadata:
  name: symbol-service
spec:
  selector:
    app: symbol-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symbol-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symbol-service
  template:
    metadata:
      labels:
        app: symbol-service
    spec:
      containers:
        - name: symbol-service
          image: your-dockerhub/symbol-service:latest
          envFrom:
            - configMapRef:
                name: alpha-oms-env
          ports:
            - containerPort: 8004
