name: Alpha OMS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip ninja-build libhiredis-dev libprotobuf-dev libgrpc++-dev protobuf-compiler libspdlog-dev libboost-all-dev
          pip3 install conan meson

      - name: Configure Conan
        run: conan profile detect

      - name: Install Conan dependencies
        run: conan install . --output-folder=build --build=missing

      - name: Configure Meson
        run: meson setup build --buildtype=release

      - name: Compile
        run: meson compile -C build
